from sympy import *
L=Line(Point(2,3), Point(4,1))
x,y=symbols('x y')
print(L)
M=Line(2*x+3*y-4)
print(M)
N=Line(Point(1,4),slope=1)
print(N)
print(L.equation())
print(L.coefficients)
S=Segment((0,0),(3,1))
print(S)
A=Ray((0,0),(3,1))
print(A)
B=Line((0,0),(0,1))
print(B.angle_between(A))
print(B.angle_between(S))
print(B.intersection(S))
print(A.length)
print(A.distance(S))
print(L.slope)
print(S.midpoint)
print(M.points)
print(M.rotate(pi/6))
M1=M.rotate(pi/6)
print(M1.equation())
Line=M.reflect(M1)
print(Line)
