from sympy import *
'''p1,p2,p3,p4,p5=map(Point,[(0,0),(1,0),(5,1),(0,1),(3,0)])
P=Polygon(p1,p2,p3,p4,p5)
print(P)
A=Polygon((0,0), 1, n=5)
print(A)
print(A.area)
print(P.angles[p2])
print(P.is_convex())
print(P.perimeter)
print(A.center)
x,y=symbols('x y')
l=Line(x-y)
print(A.reflect(l))
print(A.rotate(pi/4))
print(A.scale(2,2))
T=Triangle(p1,p2,p3)
print(T)'''
print(Triangle(sas=(1,20,4)))
print(Triangle(sss=(2,2,2)))
print(Triangle(asa=(30,5,90)))
A=Triangle(sas=(1,20,4))
print(A.is_isosceles())
print(A.is_right())
print(A.is_scalene())